(function(){function a(b,c,d){if(b===c)return 0!==b||1/b==1/c;if(null==b||null==c)return b===c;b._chain&&(b=b._wrapped);c._chain&&(c=c._wrapped);if(b.isEqual&&h.isFunction(b.isEqual))return b.isEqual(c);if(c.isEqual&&h.isFunction(c.isEqual))return c.isEqual(b);var g=j.call(b);if(g!=j.call(c))return!1;switch(g){case "[object String]":return b==""+c;case "[object Number]":return b!=+b?c!=+c:0==b?1/b==1/c:b==+c;case "[object Date]":case "[object Boolean]":return+b==+c;case "[object RegExp]":return b.source==
c.source&&b.global==c.global&&b.multiline==c.multiline&&b.ignoreCase==c.ignoreCase}if("object"!=typeof b||"object"!=typeof c)return!1;for(var e=d.length;e--;)if(d[e]==b)return!0;d.push(b);var e=0,f=!0;if("[object Array]"==g){if(e=b.length,f=e==c.length)for(;e--&&(f=e in b==e in c&&a(b[e],c[e],d)););}else{if("constructor"in b!="constructor"in c||b.constructor!=c.constructor)return!1;for(var s in b)if(h.has(b,s)&&(e++,!(f=h.has(c,s)&&a(b[s],c[s],d))))break;if(f){for(s in c)if(h.has(c,s)&&!e--)break;
f=!e}}d.pop();return f}var b=this,c=b._,e={},d=Array.prototype,g=Object.prototype,f=d.slice,i=d.unshift,j=g.toString,k=g.hasOwnProperty,l=d.forEach,m=d.map,n=d.reduce,o=d.reduceRight,q=d.filter,u=d.every,t=d.some,w=d.indexOf,v=d.lastIndexOf,g=Array.isArray,y=Object.keys,s=Function.prototype.bind,h=function(a){return new x(a)};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=h),exports._=h):b._=h;h.VERSION="1.3.1";var r=h.each=h.forEach=function(a,
b,c){if(a!=null)if(l&&a.forEach===l)a.forEach(b,c);else if(a.length===+a.length)for(var d=0,g=a.length;d<g;d++){if(d in a&&b.call(c,a[d],d,a)===e)break}else for(d in a)if(h.has(a,d)&&b.call(c,a[d],d,a)===e)break};h.map=h.collect=function(a,b,c){var d=[];if(a==null)return d;if(m&&a.map===m)return a.map(b,c);r(a,function(a,g,h){d[d.length]=b.call(c,a,g,h)});if(a.length===+a.length)d.length=a.length;return d};h.reduce=h.foldl=h.inject=function(a,b,c,d){var g=arguments.length>2;a==null&&(a=[]);if(n&&
a.reduce===n){d&&(b=h.bind(b,d));return g?a.reduce(b,c):a.reduce(b)}r(a,function(a,h,e){if(g)c=b.call(d,c,a,h,e);else{c=a;g=true}});if(!g)throw new TypeError("Reduce of empty array with no initial value");return c};h.reduceRight=h.foldr=function(a,b,c,d){var g=arguments.length>2;a==null&&(a=[]);if(o&&a.reduceRight===o){d&&(b=h.bind(b,d));return g?a.reduceRight(b,c):a.reduceRight(b)}var e=h.toArray(a).reverse();d&&!g&&(b=h.bind(b,d));return g?h.reduce(e,b,c,d):h.reduce(e,b)};h.find=h.detect=function(a,
b,c){var d;C(a,function(a,g,h){if(b.call(c,a,g,h)){d=a;return true}});return d};h.filter=h.select=function(a,b,c){var d=[];if(a==null)return d;if(q&&a.filter===q)return a.filter(b,c);r(a,function(a,g,h){b.call(c,a,g,h)&&(d[d.length]=a)});return d};h.reject=function(a,b,c){var d=[];if(a==null)return d;r(a,function(a,g,h){b.call(c,a,g,h)||(d[d.length]=a)});return d};h.every=h.all=function(a,b,c){var d=true;if(a==null)return d;if(u&&a.every===u)return a.every(b,c);r(a,function(a,g,h){if(!(d=d&&b.call(c,
a,g,h)))return e});return d};var C=h.some=h.any=function(a,b,c){b||(b=h.identity);var d=false;if(a==null)return d;if(t&&a.some===t)return a.some(b,c);r(a,function(a,g,h){if(d||(d=b.call(c,a,g,h)))return e});return!!d};h.include=h.contains=function(a,b){var c=false;if(a==null)return c;if(w&&a.indexOf===w)return a.indexOf(b)!=-1;return c=C(a,function(a){return a===b})};h.invoke=function(a,b){var c=f.call(arguments,2);return h.map(a,function(a){return(h.isFunction(b)?b||a:a[b]).apply(a,c)})};h.pluck=
function(a,b){return h.map(a,function(a){return a[b]})};h.max=function(a,b,c){if(!b&&h.isArray(a))return Math.max.apply(Math,a);if(!b&&h.isEmpty(a))return-Infinity;var d={computed:-Infinity};r(a,function(a,g,h){g=b?b.call(c,a,g,h):a;g>=d.computed&&(d={value:a,computed:g})});return d.value};h.min=function(a,b,c){if(!b&&h.isArray(a))return Math.min.apply(Math,a);if(!b&&h.isEmpty(a))return Infinity;var d={computed:Infinity};r(a,function(a,g,h){g=b?b.call(c,a,g,h):a;g<d.computed&&(d={value:a,computed:g})});
return d.value};h.shuffle=function(a){var b=[],c;r(a,function(a,d){if(d==0)b[0]=a;else{c=Math.floor(Math.random()*(d+1));b[d]=b[c];b[c]=a}});return b};h.sortBy=function(a,b,c){return h.pluck(h.map(a,function(a,d,g){return{value:a,criteria:b.call(c,a,d,g)}}).sort(function(a,b){var c=a.criteria,d=b.criteria;return c<d?-1:c>d?1:0}),"value")};h.groupBy=function(a,b){var c={},d=h.isFunction(b)?b:function(a){return a[b]};r(a,function(a,b){var g=d(a,b);(c[g]||(c[g]=[])).push(a)});return c};h.sortedIndex=
function(a,b,c){c||(c=h.identity);for(var d=0,g=a.length;d<g;){var e=d+g>>1;c(a[e])<c(b)?d=e+1:g=e}return d};h.toArray=function(a){return!a?[]:a.toArray?a.toArray():h.isArray(a)||h.isArguments(a)?f.call(a):h.values(a)};h.size=function(a){return h.toArray(a).length};h.first=h.head=function(a,b,c){return b!=null&&!c?f.call(a,0,b):a[0]};h.initial=function(a,b,c){return f.call(a,0,a.length-(b==null||c?1:b))};h.last=function(a,b,c){return b!=null&&!c?f.call(a,Math.max(a.length-b,0)):a[a.length-1]};h.rest=
h.tail=function(a,b,c){return f.call(a,b==null||c?1:b)};h.compact=function(a){return h.filter(a,function(a){return!!a})};h.flatten=function(a,b){return h.reduce(a,function(a,c){if(h.isArray(c))return a.concat(b?c:h.flatten(c));a[a.length]=c;return a},[])};h.without=function(a){return h.difference(a,f.call(arguments,1))};h.uniq=h.unique=function(a,b,c){var c=c?h.map(a,c):a,d=[];h.reduce(c,function(c,g,e){if(0==e||(b===true?h.last(c)!=g:!h.include(c,g))){c[c.length]=g;d[d.length]=a[e]}return c},[]);
return d};h.union=function(){return h.uniq(h.flatten(arguments,true))};h.intersection=h.intersect=function(a){var b=f.call(arguments,1);return h.filter(h.uniq(a),function(a){return h.every(b,function(b){return h.indexOf(b,a)>=0})})};h.difference=function(a){var b=h.flatten(f.call(arguments,1));return h.filter(a,function(a){return!h.include(b,a)})};h.zip=function(){for(var a=f.call(arguments),b=h.max(h.pluck(a,"length")),c=Array(b),d=0;d<b;d++)c[d]=h.pluck(a,""+d);return c};h.indexOf=function(a,b,
c){if(a==null)return-1;var d;if(c){c=h.sortedIndex(a,b);return a[c]===b?c:-1}if(w&&a.indexOf===w)return a.indexOf(b);c=0;for(d=a.length;c<d;c++)if(c in a&&a[c]===b)return c;return-1};h.lastIndexOf=function(a,b){if(a==null)return-1;if(v&&a.lastIndexOf===v)return a.lastIndexOf(b);for(var c=a.length;c--;)if(c in a&&a[c]===b)return c;return-1};h.range=function(a,b,c){if(arguments.length<=1){b=a||0;a=0}for(var c=arguments[2]||1,d=Math.max(Math.ceil((b-a)/c),0),g=0,h=Array(d);g<d;){h[g++]=a;a=a+c}return h};
var D=function(){};h.bind=function(a,b){var c,d;if(a.bind===s&&s)return s.apply(a,f.call(arguments,1));if(!h.isFunction(a))throw new TypeError;d=f.call(arguments,2);return c=function(){if(!(this instanceof c))return a.apply(b,d.concat(f.call(arguments)));D.prototype=a.prototype;var g=new D,h=a.apply(g,d.concat(f.call(arguments)));return Object(h)===h?h:g}};h.bindAll=function(a){var b=f.call(arguments,1);b.length==0&&(b=h.functions(a));r(b,function(b){a[b]=h.bind(a[b],a)});return a};h.memoize=function(a,
b){var c={};b||(b=h.identity);return function(){var d=b.apply(this,arguments);return h.has(c,d)?c[d]:c[d]=a.apply(this,arguments)}};h.delay=function(a,b){var c=f.call(arguments,2);return setTimeout(function(){return a.apply(a,c)},b)};h.defer=function(a){return h.delay.apply(h,[a,1].concat(f.call(arguments,1)))};h.throttle=function(a,b){var c,d,g,e,f,s=h.debounce(function(){f=e=false},b);return function(){c=this;d=arguments;g||(g=setTimeout(function(){g=null;f&&a.apply(c,d);s()},b));e?f=true:a.apply(c,
d);s();e=true}};h.debounce=function(a,b){var c;return function(){var d=this,g=arguments;clearTimeout(c);c=setTimeout(function(){c=null;a.apply(d,g)},b)}};h.once=function(a){var b=false,c;return function(){if(b)return c;b=true;return c=a.apply(this,arguments)}};h.wrap=function(a,b){return function(){var c=[a].concat(f.call(arguments,0));return b.apply(this,c)}};h.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length-1;c>=0;c--)b=[a[c].apply(this,b)];return b[0]}};h.after=
function(a,b){return a<=0?b():function(){if(--a<1)return b.apply(this,arguments)}};h.keys=y||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var b=[],c;for(c in a)h.has(a,c)&&(b[b.length]=c);return b};h.values=function(a){return h.map(a,h.identity)};h.functions=h.methods=function(a){var b=[],c;for(c in a)h.isFunction(a[c])&&b.push(c);return b.sort()};h.extend=function(a){r(f.call(arguments,1),function(b){for(var c in b)a[c]=b[c]});return a};h.defaults=function(a){r(f.call(arguments,
1),function(b){for(var c in b)a[c]==null&&(a[c]=b[c])});return a};h.clone=function(a){return!h.isObject(a)?a:h.isArray(a)?a.slice():h.extend({},a)};h.tap=function(a,b){b(a);return a};h.isEqual=function(b,c){return a(b,c,[])};h.isEmpty=function(a){if(h.isArray(a)||h.isString(a))return a.length===0;for(var b in a)if(h.has(a,b))return false;return true};h.isElement=function(a){return!!(a&&a.nodeType==1)};h.isArray=g||function(a){return j.call(a)=="[object Array]"};h.isObject=function(a){return a===Object(a)};
h.isArguments=function(a){return j.call(a)=="[object Arguments]"};h.isArguments(arguments)||(h.isArguments=function(a){return!(!a||!h.has(a,"callee"))});h.isFunction=function(a){return j.call(a)=="[object Function]"};h.isString=function(a){return j.call(a)=="[object String]"};h.isNumber=function(a){return j.call(a)=="[object Number]"};h.isNaN=function(a){return a!==a};h.isBoolean=function(a){return a===true||a===false||j.call(a)=="[object Boolean]"};h.isDate=function(a){return j.call(a)=="[object Date]"};
h.isRegExp=function(a){return j.call(a)=="[object RegExp]"};h.isNull=function(a){return a===null};h.isUndefined=function(a){return a===void 0};h.has=function(a,b){return k.call(a,b)};h.noConflict=function(){b._=c;return this};h.identity=function(a){return a};h.times=function(a,b,c){for(var d=0;d<a;d++)b.call(c,d)};h.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};h.mixin=function(a){r(h.functions(a),
function(b){E(b,h[b]=a[b])})};var F=0;h.uniqueId=function(a){var b=F++;return a?a+b:b};h.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var z=/.^/,A=function(a){return a.replace(/\\\\/g,"\\").replace(/\\'/g,"'")};h.template=function(a,b){var c=h.templateSettings,c="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(c.escape||z,function(a,b){return"',_.escape("+
A(b)+"),'"}).replace(c.interpolate||z,function(a,b){return"',"+A(b)+",'"}).replace(c.evaluate||z,function(a,b){return"');"+A(b).replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');",d=new Function("obj","_",c);return b?d(b,h):function(a){return d.call(this,a,h)}};h.chain=function(a){return h(a).chain()};var x=function(a){this._wrapped=a};h.prototype=x.prototype;var B=function(a,b){return b?h(a).chain():a},E=function(a,b){x.prototype[a]=
function(){var a=f.call(arguments);i.call(a,this._wrapped);return B(b.apply(h,a),this._chain)}};h.mixin(h);r("pop,push,reverse,shift,sort,splice,unshift".split(","),function(a){var b=d[a];x.prototype[a]=function(){var c=this._wrapped;b.apply(c,arguments);var d=c.length;(a=="shift"||a=="splice")&&d===0&&delete c[0];return B(c,this._chain)}});r(["concat","join","slice"],function(a){var b=d[a];x.prototype[a]=function(){return B(b.apply(this._wrapped,arguments),this._chain)}});x.prototype.chain=function(){this._chain=
true;return this};x.prototype.value=function(){return this._wrapped}}).call(this);(function(){var a=this,b=a.Backbone,c=Array.prototype.slice,e=Array.prototype.splice,d;d="undefined"!==typeof exports?exports:a.Backbone={};d.VERSION="0.9.1";var g=a._;!g&&"undefined"!==typeof require&&(g=require("underscore"));var f=a.jQuery||a.Zepto||a.ender;d.setDomLibrary=function(a){f=a};d.noConflict=function(){a.Backbone=b;return this};d.emulateHTTP=!1;d.emulateJSON=!1;d.Events={on:function(a,b,c){for(var d,a=a.split(/\s+/),g=this._callbacks||(this._callbacks={});d=a.shift();){d=g[d]||(g[d]=
{});var e=d.tail||(d.tail=d.next={});e.callback=b;e.context=c;d.tail=e.next={}}return this},off:function(a,b,c){var d,g,e;if(a){if(g=this._callbacks)for(a=a.split(/\s+/);d=a.shift();)if(e=g[d],delete g[d],b&&e)for(;(e=e.next)&&e.next;)if(!(e.callback===b&&(!c||e.context===c)))this.on(d,e.callback,e.context)}else delete this._callbacks;return this},trigger:function(a){var b,d,g,e;if(!(g=this._callbacks))return this;e=g.all;for((a=a.split(/\s+/)).push(null);b=a.shift();)e&&a.push({next:e.next,tail:e.tail,
event:b}),(d=g[b])&&a.push({next:d.next,tail:d.tail});for(e=c.call(arguments,1);d=a.pop();){b=d.tail;for(g=d.event?[d.event].concat(e):e;(d=d.next)!==b;)d.callback.apply(d.context||this,g)}return this}};d.Events.bind=d.Events.on;d.Events.unbind=d.Events.off;d.Model=function(a,b){var c;a||(a={});b&&b.parse&&(a=this.parse(a));if(c=v(this,"defaults"))a=g.extend({},c,a);b&&b.collection&&(this.collection=b.collection);this.attributes={};this._escapedAttributes={};this.cid=g.uniqueId("c");if(!this.set(a,
{silent:!0}))throw Error("Can't create an invalid model");delete this._changed;this._previousAttributes=g.clone(this.attributes);this.initialize.apply(this,arguments)};g.extend(d.Model.prototype,d.Events,{idAttribute:"id",initialize:function(){},toJSON:function(){return g.clone(this.attributes)},get:function(a){return this.attributes[a]},escape:function(a){var b;if(b=this._escapedAttributes[a])return b;b=this.attributes[a];return this._escapedAttributes[a]=g.escape(null==b?"":""+b)},has:function(a){return null!=
this.attributes[a]},set:function(a,b,c){var e,f;g.isObject(a)||null==a?(e=a,c=b):(e={},e[a]=b);c||(c={});if(!e)return this;e instanceof d.Model&&(e=e.attributes);if(c.unset)for(f in e)e[f]=void 0;if(!this._validate(e,c))return!1;this.idAttribute in e&&(this.id=e[this.idAttribute]);var b=this.attributes,i=this._escapedAttributes,j=this._previousAttributes||{},k=this._setting;this._changed||(this._changed={});this._setting=!0;for(f in e)if(a=e[f],g.isEqual(b[f],a)||delete i[f],c.unset?delete b[f]:b[f]=
a,this._changing&&!g.isEqual(this._changed[f],a)&&(this.trigger("change:"+f,this,a,c),this._moreChanges=!0),delete this._changed[f],!g.isEqual(j[f],a)||g.has(b,f)!=g.has(j,f))this._changed[f]=a;k||(!c.silent&&this.hasChanged()&&this.change(c),this._setting=!1);return this},unset:function(a,b){(b||(b={})).unset=!0;return this.set(a,null,b)},clear:function(a){(a||(a={})).unset=!0;return this.set(g.clone(this.attributes),a)},fetch:function(a){var a=a?g.clone(a):{},b=this,c=a.success;a.success=function(d,
g,e){if(!b.set(b.parse(d,e),a))return!1;c&&c(b,d)};a.error=d.wrapError(a.error,b,a);return(this.sync||d.sync).call(this,"read",this,a)},save:function(a,b,c){var e,f;g.isObject(a)||null==a?(e=a,c=b):(e={},e[a]=b);c=c?g.clone(c):{};c.wait&&(f=g.clone(this.attributes));a=g.extend({},c,{silent:!0});if(e&&!this.set(e,c.wait?a:c))return!1;var i=this,j=c.success;c.success=function(a,b,d){b=i.parse(a,d);c.wait&&(b=g.extend(e||{},b));if(!i.set(b,c))return false;j?j(i,a):i.trigger("sync",i,a,c)};c.error=d.wrapError(c.error,
i,c);b=this.isNew()?"create":"update";b=(this.sync||d.sync).call(this,b,this,c);c.wait&&this.set(f,a);return b},destroy:function(a){var a=a?g.clone(a):{},b=this,c=a.success,e=function(){b.trigger("destroy",b,b.collection,a)};if(this.isNew())return e();a.success=function(d){a.wait&&e();c?c(b,d):b.trigger("sync",b,d,a)};a.error=d.wrapError(a.error,b,a);var f=(this.sync||d.sync).call(this,"delete",this,a);a.wait||e();return f},url:function(){var a=v(this.collection,"url")||v(this,"urlRoot")||y();return this.isNew()?
a:a+("/"==a.charAt(a.length-1)?"":"/")+encodeURIComponent(this.id)},parse:function(a){return a},clone:function(){return new this.constructor(this.attributes)},isNew:function(){return null==this.id},change:function(a){if(this._changing||!this.hasChanged())return this;this._moreChanges=this._changing=!0;for(var b in this._changed)this.trigger("change:"+b,this,this._changed[b],a);for(;this._moreChanges;)this._moreChanges=!1,this.trigger("change",this,a);this._previousAttributes=g.clone(this.attributes);
delete this._changed;this._changing=!1;return this},hasChanged:function(a){return!arguments.length?!g.isEmpty(this._changed):this._changed&&g.has(this._changed,a)},changedAttributes:function(a){if(!a)return this.hasChanged()?g.clone(this._changed):!1;var b,c=!1,d=this._previousAttributes,e;for(e in a)if(!g.isEqual(d[e],b=a[e]))(c||(c={}))[e]=b;return c},previous:function(a){return!arguments.length||!this._previousAttributes?null:this._previousAttributes[a]},previousAttributes:function(){return g.clone(this._previousAttributes)},
isValid:function(){return!this.validate(this.attributes)},_validate:function(a,b){if(b.silent||!this.validate)return!0;var a=g.extend({},this.attributes,a),c=this.validate(a,b);if(!c)return!0;b&&b.error?b.error(this,c,b):this.trigger("error",this,c,b);return!1}});d.Collection=function(a,b){b||(b={});b.comparator&&(this.comparator=b.comparator);this._reset();this.initialize.apply(this,arguments);a&&this.reset(a,{silent:!0,parse:b.parse})};g.extend(d.Collection.prototype,d.Events,{model:d.Model,initialize:function(){},
toJSON:function(){return this.map(function(a){return a.toJSON()})},add:function(a,b){var c,d,f,i,j,k={},l={};b||(b={});a=g.isArray(a)?a.slice():[a];c=0;for(d=a.length;c<d;c++){if(!(f=a[c]=this._prepareModel(a[c],b)))throw Error("Can't add an invalid model to a collection");if(k[i=f.cid]||this._byCid[i]||null!=(j=f.id)&&(l[j]||this._byId[j]))throw Error("Can't add the same model to a collection twice");k[i]=l[j]=f}for(c=0;c<d;c++)(f=a[c]).on("all",this._onModelEvent,this),this._byCid[f.cid]=f,null!=
f.id&&(this._byId[f.id]=f);this.length+=d;e.apply(this.models,[null!=b.at?b.at:this.models.length,0].concat(a));this.comparator&&this.sort({silent:!0});if(b.silent)return this;c=0;for(d=this.models.length;c<d;c++)if(k[(f=this.models[c]).cid])b.index=c,f.trigger("add",f,this,b);return this},remove:function(a,b){var c,d,e,f;b||(b={});a=g.isArray(a)?a.slice():[a];c=0;for(d=a.length;c<d;c++)if(f=this.getByCid(a[c])||this.get(a[c]))delete this._byId[f.id],delete this._byCid[f.cid],e=this.indexOf(f),this.models.splice(e,
1),this.length--,b.silent||(b.index=e,f.trigger("remove",f,this,b)),this._removeReference(f);return this},get:function(a){return null==a?null:this._byId[null!=a.id?a.id:a]},getByCid:function(a){return a&&this._byCid[a.cid||a]},at:function(a){return this.models[a]},sort:function(a){a||(a={});if(!this.comparator)throw Error("Cannot sort a set without a comparator");var b=g.bind(this.comparator,this);1==this.comparator.length?this.models=this.sortBy(b):this.models.sort(b);a.silent||this.trigger("reset",
this,a);return this},pluck:function(a){return g.map(this.models,function(b){return b.get(a)})},reset:function(a,b){a||(a=[]);b||(b={});for(var c=0,d=this.models.length;c<d;c++)this._removeReference(this.models[c]);this._reset();this.add(a,{silent:!0,parse:b.parse});b.silent||this.trigger("reset",this,b);return this},fetch:function(a){a=a?g.clone(a):{};void 0===a.parse&&(a.parse=!0);var b=this,c=a.success;a.success=function(d,g,e){b[a.add?"add":"reset"](b.parse(d,e),a);c&&c(b,d)};a.error=d.wrapError(a.error,
b,a);return(this.sync||d.sync).call(this,"read",this,a)},create:function(a,b){var c=this,b=b?g.clone(b):{},a=this._prepareModel(a,b);if(!a)return!1;b.wait||c.add(a,b);var d=b.success;b.success=function(g,e){b.wait&&c.add(g,b);d?d(g,e):g.trigger("sync",a,e,b)};a.save(null,b);return a},parse:function(a){return a},chain:function(){return g(this.models).chain()},_reset:function(){this.length=0;this.models=[];this._byId={};this._byCid={}},_prepareModel:function(a,b){a instanceof d.Model?a.collection||
(a.collection=this):(b.collection=this,a=new this.model(a,b),a._validate(a.attributes,b)||(a=!1));return a},_removeReference:function(a){this==a.collection&&delete a.collection;a.off("all",this._onModelEvent,this)},_onModelEvent:function(a,b,c,d){("add"==a||"remove"==a)&&c!=this||("destroy"==a&&this.remove(b,d),b&&a==="change:"+b.idAttribute&&(delete this._byId[b.previous(b.idAttribute)],this._byId[b.id]=b),this.trigger.apply(this,arguments))}});g.each("forEach,each,map,reduce,reduceRight,find,detect,filter,select,reject,every,all,some,any,include,contains,invoke,max,min,sortBy,sortedIndex,toArray,size,first,initial,rest,last,without,indexOf,shuffle,lastIndexOf,isEmpty,groupBy".split(","),
function(a){d.Collection.prototype[a]=function(){return g[a].apply(g,[this.models].concat(g.toArray(arguments)))}});d.Router=function(a){a||(a={});a.routes&&(this.routes=a.routes);this._bindRoutes();this.initialize.apply(this,arguments)};var i=/:\w+/g,j=/\*\w+/g,k=/[-[\]{}()+?.,\\^$|#\s]/g;g.extend(d.Router.prototype,d.Events,{initialize:function(){},route:function(a,b,c){d.history||(d.history=new d.History);g.isRegExp(a)||(a=this._routeToRegExp(a));c||(c=this[b]);d.history.route(a,g.bind(function(g){g=
this._extractParameters(a,g);c&&c.apply(this,g);this.trigger.apply(this,["route:"+b].concat(g));d.history.trigger("route",this,b,g)},this));return this},navigate:function(a,b){d.history.navigate(a,b)},_bindRoutes:function(){if(this.routes){var a=[],b;for(b in this.routes)a.unshift([b,this.routes[b]]);b=0;for(var c=a.length;b<c;b++)this.route(a[b][0],a[b][1],this[a[b][1]])}},_routeToRegExp:function(a){a=a.replace(k,"\\$&").replace(i,"([^/]+)").replace(j,"(.*?)");return RegExp("^"+a+"$")},_extractParameters:function(a,
b){return a.exec(b).slice(1)}});d.History=function(){this.handlers=[];g.bindAll(this,"checkUrl")};var l=/^[#\/]/,m=/msie [\w.]+/,n=!1;g.extend(d.History.prototype,d.Events,{interval:50,getFragment:function(a,b){if(null==a)if(this._hasPushState||b){var a=window.location.pathname,c=window.location.search;c&&(a+=c)}else a=window.location.hash;a=decodeURIComponent(a);a.indexOf(this.options.root)||(a=a.substr(this.options.root.length));return a.replace(l,"")},start:function(a){if(n)throw Error("Backbone.history has already been started");
this.options=g.extend({},{root:"/"},this.options,a);this._wantsHashChange=!1!==this.options.hashChange;this._wantsPushState=!!this.options.pushState;this._hasPushState=!(!this.options.pushState||!window.history||!window.history.pushState);var a=this.getFragment(),b=document.documentMode;if(b=m.exec(navigator.userAgent.toLowerCase())&&(!b||7>=b))this.iframe=f('<iframe src="javascript:0" tabindex="-1" />').hide().appendTo("body")[0].contentWindow,this.navigate(a);this._hasPushState?f(window).bind("popstate",
this.checkUrl):this._wantsHashChange&&"onhashchange"in window&&!b?f(window).bind("hashchange",this.checkUrl):this._wantsHashChange&&(this._checkUrlInterval=setInterval(this.checkUrl,this.interval));this.fragment=a;n=!0;a=window.location;b=a.pathname==this.options.root;if(this._wantsHashChange&&this._wantsPushState&&!this._hasPushState&&!b)return this.fragment=this.getFragment(null,!0),window.location.replace(this.options.root+"#"+this.fragment),!0;this._wantsPushState&&this._hasPushState&&b&&a.hash&&
(this.fragment=a.hash.replace(l,""),window.history.replaceState({},document.title,a.protocol+"//"+a.host+this.options.root+this.fragment));if(!this.options.silent)return this.loadUrl()},stop:function(){f(window).unbind("popstate",this.checkUrl).unbind("hashchange",this.checkUrl);clearInterval(this._checkUrlInterval);n=!1},route:function(a,b){this.handlers.unshift({route:a,callback:b})},checkUrl:function(){var a=this.getFragment();a==this.fragment&&this.iframe&&(a=this.getFragment(this.iframe.location.hash));
if(a==this.fragment||a==decodeURIComponent(this.fragment))return!1;this.iframe&&this.navigate(a);this.loadUrl()||this.loadUrl(window.location.hash)},loadUrl:function(a){var b=this.fragment=this.getFragment(a);return g.any(this.handlers,function(a){if(a.route.test(b))return a.callback(b),!0})},navigate:function(a,b){if(!n)return!1;if(!b||!0===b)b={trigger:b};var c=(a||"").replace(l,"");this.fragment==c||this.fragment==decodeURIComponent(c)||(this._hasPushState?(0!=c.indexOf(this.options.root)&&(c=
this.options.root+c),this.fragment=c,window.history[b.replace?"replaceState":"pushState"]({},document.title,c)):this._wantsHashChange?(this.fragment=c,this._updateHash(window.location,c,b.replace),this.iframe&&c!=this.getFragment(this.iframe.location.hash)&&(b.replace||this.iframe.document.open().close(),this._updateHash(this.iframe.location,c,b.replace))):window.location.assign(this.options.root+a),b.trigger&&this.loadUrl(a))},_updateHash:function(a,b,c){c?a.replace(a.toString().replace(/(javascript:|#).*$/,
"")+"#"+b):a.hash=b}});d.View=function(a){this.cid=g.uniqueId("view");this._configure(a||{});this._ensureElement();this.initialize.apply(this,arguments);this.delegateEvents()};var o=/^(\S+)\s*(.*)$/,q="model,collection,el,id,attributes,className,tagName".split(",");g.extend(d.View.prototype,d.Events,{tagName:"div",$:function(a){return this.$el.find(a)},initialize:function(){},render:function(){return this},remove:function(){this.$el.remove();return this},make:function(a,b,c){a=document.createElement(a);
b&&f(a).attr(b);c&&f(a).html(c);return a},setElement:function(a,b){this.$el=f(a);this.el=this.$el[0];!1!==b&&this.delegateEvents();return this},delegateEvents:function(a){if(a||(a=v(this,"events"))){this.undelegateEvents();for(var b in a){var c=a[b];g.isFunction(c)||(c=this[a[b]]);if(!c)throw Error('Event "'+a[b]+'" does not exist');var d=b.match(o),e=d[1],d=d[2],c=g.bind(c,this),e=e+(".delegateEvents"+this.cid);""===d?this.$el.bind(e,c):this.$el.delegate(d,e,c)}}},undelegateEvents:function(){this.$el.unbind(".delegateEvents"+
this.cid)},_configure:function(a){this.options&&(a=g.extend({},this.options,a));for(var b=0,c=q.length;b<c;b++){var d=q[b];a[d]&&(this[d]=a[d])}this.options=a},_ensureElement:function(){if(this.el)this.setElement(this.el,!1);else{var a=v(this,"attributes")||{};this.id&&(a.id=this.id);this.className&&(a["class"]=this.className);this.setElement(this.make(this.tagName,a),!1)}}});d.Model.extend=d.Collection.extend=d.Router.extend=d.View.extend=function(a,b){var c=w(this,a,b);c.extend=this.extend;return c};
var u={create:"POST",update:"PUT","delete":"DELETE",read:"GET"};d.sync=function(a,b,c){var e=u[a],i={type:e,dataType:"json"};c.url||(i.url=v(b,"url")||y());if(!c.data&&b&&("create"==a||"update"==a))i.contentType="application/json",i.data=JSON.stringify(b.toJSON());d.emulateJSON&&(i.contentType="application/x-www-form-urlencoded",i.data=i.data?{model:i.data}:{});if(d.emulateHTTP&&("PUT"===e||"DELETE"===e))d.emulateJSON&&(i.data._method=e),i.type="POST",i.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",
e)};"GET"!==i.type&&!d.emulateJSON&&(i.processData=!1);return f.ajax(g.extend(i,c))};d.wrapError=function(a,b,c){return function(d,g){g=d===b?g:d;a?a(b,g,c):b.trigger("error",b,g,c)}};var t=function(){},w=function(a,b,c){var d;d=b&&b.hasOwnProperty("constructor")?b.constructor:function(){a.apply(this,arguments)};g.extend(d,a);t.prototype=a.prototype;d.prototype=new t;b&&g.extend(d.prototype,b);c&&g.extend(d,c);d.prototype.constructor=d;d.__super__=a.prototype;return d},v=function(a,b){return!a||!a[b]?
null:g.isFunction(a[b])?a[b]():a[b]},y=function(){throw Error('A "url" property or function must be specified');}}).call(this);var JSTACK=JSTACK||{};JSTACK.VERSION="0.1";JSTACK.AUTHORS="GING";
JSTACK.Comm=function(a,b){var c;c=function(a,c,g,f,i,j){var k,l;k=new XMLHttpRequest;k.open(a,c,!0);k.setRequestHeader("Content-Type","application/json");k.setRequestHeader("Accept","application/json");k.onreadystatechange=function(){if(4===k.readyState)switch(k.status){case 100:case 200:case 201:case 202:case 203:case 204:case 205:l=b;k.responseText!==b&&""!==k.responseText&&(l=JSON.parse(k.responseText));i(l);break;case 400:j("400 Bad Request");break;case 401:j("401 Unauthorized");break;case 403:j("403 Forbidden");
break;default:j(k.status+" Error")}};f!==b&&k.setRequestHeader("X-Auth-Token",f);g!==b?(a=JSON.stringify(g),k.send(a)):k.send()};return{get:function(a,d,g,f){c("GET",a,b,d,g,f)},post:function(a,b,g,f,i){c("POST",a,b,g,f,i)},put:function(a,b,g,f,i){c("PUT",a,b,g,f,i)},del:function(a,d,g,f){c("DELETE",a,b,d,g,f)}}}(JSTACK);
JSTACK.Utils=function(a){var b,c;b=function(a){var b="",c,f,a=a.replace(/\r\n/g,"\n");for(c=0;c<a.length;c+=1)f=a.charCodeAt(c),128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128));return b};c=function(a){for(var b="",c=0,f=0,i=0,j=0;c<a.length;)f=a.charCodeAt(c),128>f?(b+=String.fromCharCode(f),c+=1):191<f&&224>f?(i=a.charCodeAt(c+1),b+=String.fromCharCode((f&31)<<
6|i&63),c+=2):(i=a.charCodeAt(c+1),j=a.charCodeAt(c+2),b+=String.fromCharCode((f&15)<<12|(i&63)<<6|j&63),c+=3);return b};return{encode:function(c){for(var d="",g,f,i,j,k,l,m=0,c=b(c);m<c.length;)g=c.charCodeAt(m+=1),f=c.charCodeAt(m+=1),i=c.charCodeAt(m+=1),j=g>>2,g=(g&3)<<4|f>>4,k=(f&15)<<2|i>>6,l=i&63,isNaN(f)?k=l=64:isNaN(i)&&(l=64),d=d+a.Utils.keyStr.charAt(j)+Base64.keyStr.charAt(g)+a.Utils.keyStr.charAt(k)+Base64.keyStr.charAt(l);return d},decode:function(b){for(var d="",g,f,i,j,k,l=0,b=b.replace(/[^A-Za-z0-9\+\/\=]/g,
"");l<b.length;)g=a.Utils.keyStr.indexOf(b.charAt(l+=1)),f=a.Utils.keyStr.indexOf(b.charAt(l+=1)),j=a.Utils.keyStr.indexOf(b.charAt(l+=1)),k=a.Utils.keyStr.indexOf(b.charAt(l+=1)),g=g<<2|f>>4,f=(f&15)<<4|j>>2,i=(j&3)<<6|k,d+=String.fromCharCode(g),64!==j&&(d+=String.fromCharCode(f)),64!==k&&(d+=String.fromCharCode(i));return c(d)}}}(JSTACK);
JSTACK.Keystone=function(a,b){var c,e;e={DISCONNECTED:0,AUTHENTICATING:1,AUTHENTICATED:2,AUTHENTICATION_ERROR:3};c={url:b,currentstate:b,access:b,token:b};return{STATES:e,params:c,init:function(a){c.url=a;c.access=b;c.token=b;c.currentstate=e.DISCONNECTED},authenticate:function(d,g,f,i,j,k){var l={},l=f!==b?{auth:{token:{id:f}}}:{auth:{passwordCredentials:{username:d,password:g}}};i!==b&&(l.auth.tenantId=i);c.currentstate=e.AUTHENTICATING;a.Comm.post(c.url+"tokens",l,b,function(d){c.currentstate=
a.Keystone.STATES.AUTHENTICATED;c.access=d.access;c.token=c.access.token.id;j!==b&&j(d)},function(a){c.currentstate=e.AUTHENTICATION_ERROR;k(a)})},gettenants:function(d){c.currentstate===a.Keystone.STATES.AUTHENTICATED&&a.Comm.get(c.url+"tenants",c.token,function(a){d!==b&&d(a)},function(a){throw Error(a);})},getservice:function(a){var g,f;if(c.currentstate!==e.AUTHENTICATED)return b;for(g in c.access.serviceCatalog)if(c.access.serviceCatalog[g]!==b&&(f=c.access.serviceCatalog[g],a===f.type))return f;
return b},getservicelist:function(){return c.currentstate!==e.AUTHENTICATED?b:c.access.serviceCatalog}}}(JSTACK);
JSTACK.Nova=function(a,b){var c,e,d;c=b;e=function(){return a.Keystone!==b&&a.Keystone.params.currentstate===a.Keystone.STATES.AUTHENTICATED?(c=a.Keystone.getservice("compute").endpoints[0].adminURL,!0):!1};d=function(d,f,i,j){e()&&(d=c+"/servers/"+d+"/action",a.Comm.post(d,f,a.Keystone.params.token,function(a){j!==b&&j(a)},function(a){throw Error(a);}))};return{getserverlist:function(d,f,i){var j;e()&&(j=c+"/servers",d!==b&d&&(j+="/detail"),f&&(j+="?all_tenants="+f),a.Comm.get(j,a.Keystone.params.token,
function(a){i!==b&&i(a)},function(a){throw Error(a);}))},getserverdetail:function(d,f){var i;e()&&(i=c+"/servers/"+d,a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getserverips:function(d,f,i){e()&&(d=c+"/servers/"+d+"/ips",f!==b&&(d+="/"+f),a.Comm.get(d,a.Keystone.params.token,function(a){i!==b&&i(a)},function(a){throw Error(a);}))},updateserver:function(d,f,i){e()&&(d=c+"/servers/"+d,f!==b&&a.Comm.put(d,{server:{name:f}},a.Keystone.params.token,function(a){i!==
b&&i(a)},function(a){throw Error(a);}))},createserver:function(d,f,i,j,k,l,m,n,o,q){var u=[],t;if(e()){d={server:{name:d,imageRef:f,flavorRef:i}};j!==b&&(d.server.key_name=j);k!==b&&(d.server.user_data=a.Utils.encode(k));if(l!==b){for(t in l)l[t]!==b&&(j={name:l[t]},u.push(j));d.server.security_groups=u}m===b&&(m=1);d.server.min_count=m;n===b&&(n=1);d.server.max_count=n;o!==b&&(d.server.availability_zone=a.Utils.encode(o));a.Comm.post(c+"/servers",d,a.Keystone.params.token,function(a){q!==b&&q(a)},
function(a){throw Error(a);})}},deleteserver:function(d,f){var i;e()&&(i=c+"/servers/"+d,a.Comm.del(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},changepasswordserver:function(a,c,e){c!==b&&d(a,{changePassword:{adminPass:c}},e)},rebootserverhard:function(a,b){d(a,{reboot:{type:"HARD"}},b)},rebootserversoft:function(a,b){d(a,{reboot:{type:"SOFT"}},b)},resizeserver:function(a,b,c){d(a,{resize:{flavorRef:b}},c)},confirmresizedserver:function(a,b){d(a,{confirmResize:null},
b)},revertresizedserver:function(a,b){d(a,{revertResize:null},b)},startserver:function(a,b){d(a,{"os-start":null},b)},stopserver:function(a,b){d(a,{"os-stop":null},b)},pauseserver:function(a,b){d(a,{pause:null},b)},unpauseserver:function(a,b){d(a,{unpause:null},b)},suspendserver:function(a,b){d(a,{suspend:null},b)},resumeserver:function(a,b){d(a,{resume:null},b)},createimage:function(a,c,e,j){c={createImage:{name:c}};c.createImage.metadata={};e!==b&&(c.createImage.metadata=e);d(a,c,j)},getflavorlist:function(d,
f){var i;e()&&(i=c+"/flavors",d!==b&d&&(i+="/detail"),a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getflavordetail:function(d,f){var i;e()&&(i=c+"/flavors/"+d,a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},createflavor:function(d,f,i,j,k,l,m,n,o){var q;e()&&(q=c+"/flavors",d={flavor:{name:d,ram:f,vcpus:i,disk:j,id:k,swap:0,"OS-FLV-EXT-DATA:ephemeral":0,rxtx_factor:0}},l!==b&&(d.flavor["OS-FLV-EXT-DATA:ephemeral"]=
l),m!==b&&(d.flavor.swap=m),n!==b&&(d.flavor.rxtx_factor=n),a.Comm.post(q,d,a.Keystone.params.token,function(a){o!==b&&o(a)},function(a){throw Error(a);}))},deleteflavor:function(d,f){var i;e()&&(i=c+"/flavors/"+d,a.Comm.del(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getimagelist:function(d,f){var i;e()&&(i=c+"/images",d!==b&d&&(i+="/detail"),a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getimagedetail:function(d,
f){var i;e()&&(i=c+"/images/"+d,a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},deleteimage:function(d,f){var i;e()&&(i=c+"/images/"+d,a.Comm.del(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getkeypairlist:function(d){var f;e()&&(f=c+"/os-keypairs",a.Comm.get(f,a.Keystone.params.token,function(a){d!==b&&d(a)},function(a){throw Error(a);}))},createkeypair:function(d,f,i){var j;e()&&(j=c+"/os-keypairs",d={keypair:{name:d}},
f!==b&&(d.keypair.public_key=f),a.Comm.post(j,d,a.Keystone.params.token,function(a){i!==b&&i(a)},function(a){throw Error(a);}))},deletekeypair:function(d,f){var i;e()&&(i=c+"/os-keypairs/"+d,a.Comm.del(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},getvncconsole:function(a,c,i){if(e()){if(c===b||!c)c="novnc";d(a,{"os-getVNCConsole":{type:c}},null,i)}},getconsoleoutput:function(a,c,i){if(e()){if(c===b||!c)c=35;d(a,{"os-getConsoleOutput":{length:c}},null,i)}},getattachedvolumes:function(d,
f){var i;e()&&(i=c+"/servers/"+d+"/os-volume_attachments",a.Comm.get(i,a.Keystone.params.token,function(a){f!==b&&f(a)},function(a){throw Error(a);}))},attachvolume:function(d,f,i,j){e()&&(d=c+"/servers/"+d+"/os-volume_attachments",f===b||i===b||a.Comm.post(d,{volumeAttachment:{volumeId:f,device:i}},a.Keystone.params.token,function(a){j!==b&&j(a)},function(a){throw Error(a);}))},detachvolume:function(d,f,i){e()&&(d=c+"/servers/"+d+"/os-volume_attachments/"+f,f!==b&&a.Comm.del(d,a.Keystone.params.token,
function(a){i!==b&&i(a)},function(a){throw Error(a);}))},getattachedvolume:function(d,f,i){e()&&(d=c+"/servers/"+d+"/os-volume_attachments/"+f,f!==b&&a.Comm.get(d,a.Keystone.params.token,function(a){i!==b&&i(a)},function(a){throw Error(a);}))}}}(JSTACK);
JSTACK.Nova.Volume=function(a,b){var c,e;c=b;e=function(){return a.Keystone!==b&&a.Keystone.params.currentstate===a.Keystone.STATES.AUTHENTICATED?(c=a.Keystone.getservice("volume").endpoints[0].adminURL,!0):!1};return{getvolumelist:function(d,g){var f;e()&&(f=c+"/volumes",d!==b&d&&(f+="/detail"),a.Comm.get(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))},createvolume:function(d,g,f,i){e()&&(d={volume:{size:d}},g!==b&&(d.volume.display_name=g),f!==b&&(d.volume.display_description=
f),a.Comm.post(c+"/volumes",d,a.Keystone.params.token,function(a){i!==b&&i(a)},function(a){throw Error(a);}))},deletevolume:function(d,g){var f;e()&&(f=c+"/volumes/"+d,a.Comm.del(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))},getvolume:function(d,g){var f;e()&&(f=c+"/volumes/"+d,a.Comm.get(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))},getsnapshotlist:function(d,g){var f;e()&&(f=c+"/snapshots",d!==b&&d&&(f+="/detail"),a.Comm.get(f,
a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))},createsnapshot:function(d,g,f,i){e()&&(d={snapshot:{volume_id:d,force:!0}},g!==b&&(d.snapshot.display_name=g),f!==b&&(d.snapshot.display_description=f),a.Comm.post(c+"/snapshots",d,a.Keystone.params.token,function(a){i!==b&&i(a)},function(a){throw Error(a);}))},deletesnapshot:function(d,g){var f;e()&&(f=c+"/snapshots/"+d,a.Comm.del(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))},getsnapshot:function(d,
g){var f;e()&&(f=c+"/snapshots/"+d,a.Comm.get(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))}}}(JSTACK);
JSTACK.Glance=function(a,b){var c,e;c=b;e=function(){return a.Keystone!==b&&a.Keystone.params.currentstate===a.Keystone.STATES.AUTHENTICATED?(c=a.Keystone.getservice("image").endpoints[0].adminURL,!0):!1};return{getimagelist:function(d,g){var f;e()&&(f=c+"/images",d!==b&&d&&(f+="/detail"),a.Comm.get(f,a.Keystone.params.token,function(a){g!==b&&g(a)},function(a){throw Error(a);}))}}}(JSTACK);!function(a){a(function(){"use strict";var b=a.support,c=(document.body||document.documentElement).style;if(c=void 0!==c.transition||void 0!==c.WebkitTransition||void 0!==c.MozTransition||void 0!==c.MsTransition||void 0!==c.OTransition)c={end:"TransitionEnd"};b.transition=c})}(window.jQuery);
!function(a){var b=function(b){a(b).on("click",'[data-dismiss="alert"]',this.close)};b.prototype={constructor:b,close:function(b){function e(){f.trigger("closed").remove()}var d=a(this),g=d.attr("data-target"),f;g||(g=d.attr("href"),g=g&&g.replace(/.*(?=#[^\s]*$)/,""));f=a(g);f.trigger("close");b&&b.preventDefault();f.length||(f=d.hasClass("alert")?d:d.parent());f.trigger("close").removeClass("in");a.support.transition&&f.hasClass("fade")?f.on(a.support.transition.end,e):e()}};a.fn.alert=function(c){return this.each(function(){var e=
a(this),d=e.data("alert");d||e.data("alert",d=new b(this));"string"==typeof c&&d[c].call(e)})};a.fn.alert.Constructor=b;a(function(){a("body").on("click.alert.data-api",'[data-dismiss="alert"]',b.prototype.close)})}(window.jQuery);
!function(a){var b=function(b,e){this.$element=a(b);this.options=a.extend({},a.fn.button.defaults,e)};b.prototype={constructor:b,setState:function(a){var b=this.$element,d=b.data(),g=b.is("input")?"val":"html",a=a+"Text";d.resetText||b.data("resetText",b[g]());b[g](d[a]||this.options[a]);setTimeout(function(){"loadingText"==a?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)},toggle:function(){var a=this.$element.parent('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")}};a.fn.button=function(c){return this.each(function(){var e=a(this),d=e.data("button"),g="object"==typeof c&&c;d||e.data("button",d=new b(this,g));"toggle"==c?d.toggle():c&&d.setState(c)})};a.fn.button.defaults={loadingText:"loading..."};a.fn.button.Constructor=b;a(function(){a("body").on("click.button.data-api","[data-toggle^=button]",function(b){b=a(b.target);b.hasClass("btn")||(b=b.closest(".btn"));b.button("toggle")})})}(window.jQuery);
!function(a){var b=function(b,e){this.$element=a(b);this.options=a.extend({},a.fn.carousel.defaults,e);this.options.slide&&this.slide(this.options.slide)};b.prototype={cycle:function(){return this.interval=setInterval(a.proxy(this.next,this),this.options.interval),this},to:function(b){var e=this.$element.find(".active"),d=e.parent().children(),e=d.index(e),g=this;return b>d.length-1||0>b?void 0:this.sliding?this.$element.one("slid",function(){g.to(b)}):e==b?this.pause().cycle():this.slide(b>e?"next":
"prev",a(d[b]))},pause:function(){return clearInterval(this.interval),this.interval=null,this},next:function(){return this.sliding?void 0:this.slide("next")},prev:function(){return this.sliding?void 0:this.slide("prev")},slide:function(b,e){var d=this.$element.find(".active"),g=e||d[b](),f=this.interval,i="next"==b?"left":"right",j="next"==b?"first":"last",k=this;return!g.length?void 0:(this.sliding=!0,f&&this.pause(),g=g.length?g:this.$element.find(".item")[j](),!a.support.transition&&this.$element.hasClass("slide")?
(this.$element.trigger("slide"),d.removeClass("active"),g.addClass("active"),this.sliding=!1,this.$element.trigger("slid")):(g.addClass(b),d.addClass(i),g.addClass(i),this.$element.trigger("slide"),this.$element.one(a.support.transition.end,function(){g.removeClass([b,i].join(" ")).addClass("active");d.removeClass(["active",i].join(" "));k.sliding=!1;setTimeout(function(){k.$element.trigger("slid")},0)})),f&&this.cycle(),this)}};a.fn.carousel=function(c){return this.each(function(){var e=a(this),
d=e.data("carousel"),g="object"==typeof c&&c;d||e.data("carousel",d=new b(this,g));"number"==typeof c?d.to(c):"string"==typeof c||(c=g.slide)?d[c]():d.cycle()})};a.fn.carousel.defaults={interval:5E3};a.fn.carousel.Constructor=b;a(function(){a("body").on("click.carousel.data-api","[data-slide]",function(b){var e=a(this),d,g=a(e.attr("data-target")||(d=e.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),e=!g.data("modal")&&a.extend({},g.data(),e.data());g.carousel(e);b.preventDefault()})})}(window.jQuery);
!function(a){var b=function(b,e){this.$element=a(b);this.options=a.extend({},a.fn.collapse.defaults,e);this.options.parent&&(this.$parent=a(this.options.parent));this.options.toggle&&this.toggle()};b.prototype={constructor:b,dimension:function(){return this.$element.hasClass("width")?"width":"height"},show:function(){var b=this.dimension(),e=a.camelCase(["scroll",b].join("-")),d=this.$parent&&this.$parent.find(".in"),g;d&&d.length&&(g=d.data("collapse"),d.collapse("hide"),g||d.data("collapse",null));
this.$element[b](0);this.transition("addClass","show","shown");this.$element[b](this.$element[0][e])},hide:function(){var a=this.dimension();this.reset(this.$element[a]());this.transition("removeClass","hide","hidden");this.$element[a](0)},reset:function(a){var b=this.dimension();this.$element.removeClass("collapse")[b](a||"auto")[0].offsetWidth;this.$element.addClass("collapse")},transition:function(b,e,d){var g=this,f=function(){"show"==e&&g.reset();g.$element.trigger(d)};this.$element.trigger(e)[b]("in");
a.support.transition&&this.$element.hasClass("collapse")?this.$element.one(a.support.transition.end,f):f()},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};a.fn.collapse=function(c){return this.each(function(){var e=a(this),d=e.data("collapse"),g="object"==typeof c&&c;d||e.data("collapse",d=new b(this,g));"string"==typeof c&&d[c]()})};a.fn.collapse.defaults={toggle:!0};a.fn.collapse.Constructor=b;a(function(){a("body").on("click.collapse.data-api","[data-toggle=collapse]",function(b){var e=
a(this),d,b=e.attr("data-target")||b.preventDefault()||(d=e.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""),e=a(b).data("collapse")?"toggle":e.data();a(b).collapse(e)})})}(window.jQuery);
!function(a){function b(){a(c).parent().removeClass("open")}"use strict";var c='[data-toggle="dropdown"]',e=function(b){var c=a(b).on("click.dropdown.data-api",this.toggle);a("html").on("click.dropdown.data-api",function(){c.parent().removeClass("open")})};e.prototype={constructor:e,toggle:function(){var c=a(this),e=c.attr("data-target"),f,i;return e||(e=c.attr("href"),e=e&&e.replace(/.*(?=#[^\s]*$)/,"")),f=a(e),f.length||(f=c.parent()),i=f.hasClass("open"),b(),!i&&f.toggleClass("open"),!1}};a.fn.dropdown=
function(b){return this.each(function(){var c=a(this),f=c.data("dropdown");f||c.data("dropdown",f=new e(this));"string"==typeof b&&f[b].call(c)})};a.fn.dropdown.Constructor=e;a(function(){a("html").on("click.dropdown.data-api",b);a("body").on("click.dropdown.data-api",c,e.prototype.toggle)})}(window.jQuery);
!function(a){function b(){var b=this,d=setTimeout(function(){b.$element.off(a.support.transition.end);c.call(b)},500);this.$element.one(a.support.transition.end,function(){clearTimeout(d);c.call(b)})}function c(){this.$element.hide().trigger("hidden");e.call(this)}function e(b){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var e=a.support.transition&&c;this.$backdrop=a('<div class="modal-backdrop '+c+'" />').appendTo(document.body);"static"!=this.options.backdrop&&
this.$backdrop.click(a.proxy(this.hide,this));e&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");e?this.$backdrop.one(a.support.transition.end,b):b()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),a.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(a.support.transition.end,a.proxy(d,this)):d.call(this)):b&&b()}function d(){this.$backdrop.remove();this.$backdrop=null}function g(){var b=this;this.isShown&&this.options.keyboard?a(document).on("keyup.dismiss.modal",
function(a){27==a.which&&b.hide()}):this.isShown||a(document).off("keyup.dismiss.modal")}"use strict";var f=function(b,c){this.options=c;this.$element=a(b).delegate('[data-dismiss="modal"]',"click.dismiss.modal",a.proxy(this.hide,this))};f.prototype={constructor:f,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var b=this;this.isShown||(a("body").addClass("modal-open"),this.isShown=!0,this.$element.trigger("show"),g.call(this),e.call(this,function(){var c=a.support.transition&&
b.$element.hasClass("fade");!b.$element.parent().length&&b.$element.appendTo(document.body);b.$element.show();c&&b.$element[0].offsetWidth;b.$element.addClass("in");c?b.$element.one(a.support.transition.end,function(){b.$element.trigger("shown")}):b.$element.trigger("shown")}))},hide:function(d){d&&d.preventDefault();this.isShown&&(this.isShown=!1,a("body").removeClass("modal-open"),g.call(this),this.$element.trigger("hide").removeClass("in"),a.support.transition&&this.$element.hasClass("fade")?b.call(this):
c.call(this))}};a.fn.modal=function(b){return this.each(function(){var c=a(this),d=c.data("modal"),e=a.extend({},a.fn.modal.defaults,c.data(),"object"==typeof b&&b);d||c.data("modal",d=new f(this,e));"string"==typeof b?d[b]():e.show&&d.show()})};a.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};a.fn.modal.Constructor=f;a(function(){a("body").on("click.modal.data-api",'[data-toggle="modal"]',function(b){var c=a(this),d,e=a(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),
c=e.data("modal")?"toggle":a.extend({},e.data(),c.data());b.preventDefault();e.modal(c)})})}(window.jQuery);
!function(a){var b=function(a,b){this.init("tooltip",a,b)};b.prototype={constructor:b,init:function(b,e,d){var g,f;this.type=b;this.$element=a(e);this.options=this.getOptions(d);this.enabled=!0;"manual"!=this.options.trigger&&(g="hover"==this.options.trigger?"mouseenter":"focus",f="hover"==this.options.trigger?"mouseleave":"blur",this.$element.on(g,this.options.selector,a.proxy(this.enter,this)),this.$element.on(f,this.options.selector,a.proxy(this.leave,this)));this.options.selector?this._options=
a.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(b){return b=a.extend({},a.fn[this.type].defaults,b,this.$element.data()),b.delay&&"number"==typeof b.delay&&(b.delay={show:b.delay,hide:b.delay}),b},enter:function(b){var e=a(b.currentTarget)[this.type](this._options).data(this.type);!e.options.delay||!e.options.delay.show?e.show():(e.hoverState="in",setTimeout(function(){"in"==e.hoverState&&e.show()},e.options.delay.show))},leave:function(b){var e=a(b.currentTarget)[this.type](this._options).data(this.type);
!e.options.delay||!e.options.delay.hide?e.hide():(e.hoverState="out",setTimeout(function(){"out"==e.hoverState&&e.hide()},e.options.delay.hide))},show:function(){var a,b,d,g,f,i,j;if(this.hasContent()&&this.enabled){a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");i="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;b=/in/.test(i);a.remove().css({top:0,left:0,display:"block"}).appendTo(b?this.$element:document.body);
d=this.getPosition(b);g=a[0].offsetWidth;f=a[0].offsetHeight;switch(b?i.split(" ")[1]:i){case "bottom":j={top:d.top+d.height,left:d.left+d.width/2-g/2};break;case "top":j={top:d.top-f,left:d.left+d.width/2-g/2};break;case "left":j={top:d.top+d.height/2-f/2,left:d.left-g};break;case "right":j={top:d.top+d.height/2-f/2,left:d.left+d.width}}a.css(j).addClass(i).addClass("in")}},setContent:function(){var a=this.tip();a.find(".tooltip-inner").html(this.getTitle());a.removeClass("fade in top bottom left right")},
hide:function(){function b(){var c=setTimeout(function(){e.off(a.support.transition.end).remove()},500);e.one(a.support.transition.end,function(){clearTimeout(c);e.remove()})}var e=this.tip();e.removeClass("in");a.support.transition&&this.$tip.hasClass("fade")?b():e.remove()},fixTitle:function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},
getPosition:function(b){return a.extend({},b?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a,b=this.$element,d=this.options;return a=b.attr("data-original-title")||("function"==typeof d.title?d.title.call(b[0]):d.title),a=a.toString().replace(/(^\s*|\s*$)/,""),a},tip:function(){return this.$tip=this.$tip||a(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.$element=
null,this.options=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()}};a.fn.tooltip=function(c){return this.each(function(){var e=a(this),d=e.data("tooltip"),g="object"==typeof c&&c;d||e.data("tooltip",d=new b(this,g));"string"==typeof c&&d[c]()})};a.fn.tooltip.Constructor=b;a.fn.tooltip.defaults={animation:!0,delay:0,selector:!1,placement:"top",trigger:"hover",
title:"",template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'}}(window.jQuery);
!function(a){var b=function(a,b){this.init("popover",a,b)};b.prototype=a.extend({},a.fn.tooltip.Constructor.prototype,{constructor:b,setContent:function(){var b=this.tip(),e=this.getTitle(),d=this.getContent();b.find(".popover-title")["object"==a.type(e)?"append":"html"](e);b.find(".popover-content > *")["object"==a.type(d)?"append":"html"](d);b.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a,b=this.$element,
d=this.options;return a=b.attr("data-content")||("function"==typeof d.content?d.content.call(b[0]):d.content),a=a.toString().replace(/(^\s*|\s*$)/,""),a},tip:function(){return this.$tip||(this.$tip=a(this.options.template)),this.$tip}});a.fn.popover=function(c){return this.each(function(){var e=a(this),d=e.data("popover"),g="object"==typeof c&&c;d||e.data("popover",d=new b(this,g));"string"==typeof c&&d[c]()})};a.fn.popover.Constructor=b;a.fn.popover.defaults=a.extend({},a.fn.tooltip.defaults,{placement:"right",
content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>'})}(window.jQuery);
!function(a){function b(b,e){var d=a.proxy(this.process,this),g=a(b).is("body")?a(window):a(b),f;this.options=a.extend({},a.fn.scrollspy.defaults,e);this.$scrollElement=g.on("scroll.scroll.data-api",d);this.selector=(this.options.target||(f=a(b).attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.$body=a("body").on("click.scroll.data-api",this.selector,d);this.refresh();this.process()}"use strict";b.prototype={constructor:b,refresh:function(){this.targets=this.$body.find(this.selector).map(function(){var b=
a(this).attr("href");return/^#\w/.test(b)&&a(b).length?b:null});this.offsets=a.map(this.targets,function(b){return a(b).position().top})},process:function(){var a=this.$scrollElement.scrollTop()+this.options.offset,b=this.offsets,d=this.targets,g=this.activeTarget,f;for(f=b.length;f--;)g!=d[f]&&a>=b[f]&&(!b[f+1]||a<=b[f+1])&&this.activate(d[f])},activate:function(a){this.activeTarget=a;this.$body.find(this.selector).parent(".active").removeClass("active");a=this.$body.find(this.selector+'[href="'+
a+'"]').parent("li").addClass("active");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active")}};a.fn.scrollspy=function(c){return this.each(function(){var e=a(this),d=e.data("scrollspy"),g="object"==typeof c&&c;d||e.data("scrollspy",d=new b(this,g));"string"==typeof c&&d[c]()})};a.fn.scrollspy.Constructor=b;a.fn.scrollspy.defaults={offset:10};a(function(){a('[data-spy="scroll"]').each(function(){var b=a(this);b.scrollspy(b.data())})})}(window.jQuery);
!function(a){var b=function(b){this.element=a(b)};b.prototype={constructor:b,show:function(){var b=this.element,e=b.closest("ul:not(.dropdown-menu)"),d=b.attr("data-target"),g;d||(d=b.attr("href"),d=d&&d.replace(/.*(?=#[^\s]*$)/,""));b.parent("li").hasClass("active")||(g=e.find(".active a").last()[0],b.trigger({type:"show",relatedTarget:g}),d=a(d),this.activate(b.parent("li"),e),this.activate(d,d.parent(),function(){b.trigger({type:"shown",relatedTarget:g})}))},activate:function(b,e,d){function g(){f.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");
b.addClass("active");i?(b[0].offsetWidth,b.addClass("in")):b.removeClass("fade");b.parent(".dropdown-menu")&&b.closest("li.dropdown").addClass("active");d&&d()}var f=e.find("> .active"),i=d&&a.support.transition&&f.hasClass("fade");i?f.one(a.support.transition.end,g):g();f.removeClass("in")}};a.fn.tab=function(c){return this.each(function(){var e=a(this),d=e.data("tab");d||e.data("tab",d=new b(this));"string"==typeof c&&d[c]()})};a.fn.tab.Constructor=b;a(function(){a("body").on("click.tab.data-api",
'[data-toggle="tab"], [data-toggle="pill"]',function(b){b.preventDefault();a(this).tab("show")})})}(window.jQuery);
!function(a){var b=function(b,e){this.$element=a(b);this.options=a.extend({},a.fn.typeahead.defaults,e);this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.$menu=a(this.options.menu).appendTo("body");this.source=this.options.source;this.shown=!1;this.listen()};b.prototype={constructor:b,select:function(){return this.$element.val(this.$menu.find(".active").attr("data-value")),this.hide()},show:function(){var b=
a.extend({},this.$element.offset(),{height:this.$element[0].offsetHeight});return this.$menu.css({top:b.top+b.height,left:b.left}),this.$menu.show(),this.shown=!0,this},hide:function(){return this.$menu.hide(),this.shown=!1,this},lookup:function(){var b=this,e;return this.query=this.$element.val(),this.query?(e=a.grep(this.source,function(a){if(b.matcher(a))return a}),e=this.sorter(e),e.length?this.render(e.slice(0,this.options.items)).show():this.shown?this.hide():this):this.shown?this.hide():this},
matcher:function(a){return~a.toLowerCase().indexOf(this.query.toLowerCase())},sorter:function(a){for(var b=[],d=[],g=[],f;f=a.shift();)f.toLowerCase().indexOf(this.query.toLowerCase())?~f.indexOf(this.query)?d.push(f):g.push(f):b.push(f);return b.concat(d,g)},highlighter:function(a){return a.replace(RegExp("("+this.query+")","ig"),function(a,b){return"<strong>"+b+"</strong>"})},render:function(b){var e=this;return b=a(b).map(function(b,c){return b=a(e.options.item).attr("data-value",c),b.find("a").html(e.highlighter(c)),
b[0]}),b.first().addClass("active"),this.$menu.html(b),this},next:function(){var b=this.$menu.find(".active").removeClass("active").next();b.length||(b=a(this.$menu.find("li")[0]));b.addClass("active")},prev:function(){var a=this.$menu.find(".active").removeClass("active").prev();a.length||(a=this.$menu.find("li").last());a.addClass("active")},listen:function(){this.$element.on("blur",a.proxy(this.blur,this)).on("keypress",a.proxy(this.keypress,this)).on("keyup",a.proxy(this.keyup,this));(a.browser.webkit||
a.browser.msie)&&this.$element.on("keydown",a.proxy(this.keypress,this));this.$menu.on("click",a.proxy(this.click,this)).on("mouseenter","li",a.proxy(this.mouseenter,this))},keyup:function(a){a.stopPropagation();a.preventDefault();switch(a.keyCode){case 40:case 38:break;case 9:case 13:if(!this.shown)break;this.select();break;case 27:this.hide();break;default:this.lookup()}},keypress:function(a){a.stopPropagation();if(this.shown)switch(a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:a.preventDefault();
this.prev();break;case 40:a.preventDefault(),this.next()}},blur:function(a){var b=this;a.stopPropagation();a.preventDefault();setTimeout(function(){b.hide()},150)},click:function(a){a.stopPropagation();a.preventDefault();this.select()},mouseenter:function(b){this.$menu.find(".active").removeClass("active");a(b.currentTarget).addClass("active")}};a.fn.typeahead=function(c){return this.each(function(){var e=a(this),d=e.data("typeahead"),g="object"==typeof c&&c;d||e.data("typeahead",d=new b(this,g));
"string"==typeof c&&d[c]()})};a.fn.typeahead.defaults={source:[],items:8,menu:'<ul class="typeahead dropdown-menu"></ul>',item:'<li><a href="#"></a></li>'};a.fn.typeahead.Constructor=b;a(function(){a("body").on("focus.typeahead.data-api",'[data-provide="typeahead"]',function(b){var e=a(this);e.data("typeahead")||(b.preventDefault(),e.typeahead(e.data()))})})}(window.jQuery);(function(a,b){function c(){this._state=[];this._defaults={classHolder:"sbHolder",classHolderDisabled:"sbHolderDisabled",classSelector:"sbSelector",classOptions:"sbOptions",classGroup:"sbGroup",classSub:"sbSub",classDisabled:"sbDisabled",classToggleOpen:"sbToggleOpen",classToggle:"sbToggle",speed:200,effect:"slide",onChange:null,onOpen:null,onClose:null}}var e=!0;a.extend(c.prototype,{_isOpenSelectbox:function(a){return!a?!1:this._getInst(a).isOpen},_isDisabledSelectbox:function(a){return!a?!1:this._getInst(a).isDisabled},
_attachSelectbox:function(b,c){function f(){var b,c=this.attr("id").split("_")[1];for(b in k._state)b!==c&&k._state.hasOwnProperty(b)&&a(":input[sb='"+b+"']")[0]&&k._closeSelectbox(a(":input[sb='"+b+"']")[0])}function i(c,g){var f=g&&g.sub?!0:!1,h=g&&g.disabled?!0:!1;c.each(function(c){var g=a(this),i=a("<li>");g.is(":selected")&&(n.text(g.text()),u=e);c===w-1&&i.addClass("last");c=!g.is(":disabled")&&!h?a("<a>",{href:"#"+g.val(),rel:g.val(),text:g.text(),click:function(c){c.preventDefault();o.attr("id").split("_");
k._changeSelectbox(b,a(this).attr("rel"),a(this).text());k._closeSelectbox(b)}}):a("<span>",{text:g.text()}).addClass(l.settings.classDisabled);f&&c.addClass(l.settings.classSub);c.appendTo(i);i.appendTo(q)})}if(this._getInst(b))return!1;var j=a(b),k=this,l=k._newInst(j),m,n,o,q,u=!1;j.find("optgroup");var t=j.find("option"),w=t.length;j.attr("sb",l.uid);a.extend(l.settings,k._defaults,c);k._state[l.uid]=!1;j.hide();m=a("<div>",{id:"sbHolder_"+l.uid,"class":l.settings.classHolder});n=a("<a>",{id:"sbSelector_"+
l.uid,href:"#","class":l.settings.classSelector,click:function(c){c.preventDefault();f.apply(a(this),[]);c=a(this).attr("id").split("_")[1];k._state[c]?k._closeSelectbox(b):k._openSelectbox(b)}});o=a("<a>",{id:"sbToggle_"+l.uid,href:"#","class":l.settings.classToggle,click:function(c){c.preventDefault();f.apply(a(this),[]);c=a(this).attr("id").split("_")[1];k._state[c]?k._closeSelectbox(b):k._openSelectbox(b)}});o.appendTo(m);q=a("<ul>",{id:"sbOptions_"+l.uid,"class":l.settings.classOptions,css:{display:"none"}});
j.children().each(function(){var b=a(this),c,d={};b.is("option")?i(b):b.is("optgroup")&&(c=a("<li>"),a("<span>",{text:b.attr("label")}).addClass(l.settings.classGroup).appendTo(c),c.appendTo(q),b.is(":disabled")&&(d.disabled=!0),d.sub=!0,i(b.find("option"),d))});u||n.text(t.first().text());a.data(b,"selectbox",l);n.appendTo(m);q.appendTo(m);m.insertAfter(j)},_detachSelectbox:function(b){var c=this._getInst(b);if(!c)return!1;a("#sbHolder_"+c.uid).remove();a.data(b,"selectbox",null);a(b).show()},_changeSelectbox:function(b,
c,f){var i=this._getInst(b),j=this._get(i,"onChange");a("#sbSelector_"+i.uid).text(f);a(b).find("option[value='"+c+"']").attr("selected",e);j?j.apply(i.input?i.input[0]:null,[c,i]):i.input&&i.input.trigger("change")},_enableSelectbox:function(b){var c=this._getInst(b);if(!c||!c.isDisabled)return!1;a("#sbHolder_"+c.uid).removeClass(c.settings.classHolderDisabled);c.isDisabled=!1;a.data(b,"selectbox",c)},_disableSelectbox:function(b){var c=this._getInst(b);if(!c||c.isDisabled)return!1;a("#sbHolder_"+
c.uid).addClass(c.settings.classHolderDisabled);c.isDisabled=e;a.data(b,"selectbox",c)},_optionSelectbox:function(b,c,e){var i=this._getInst(b);if(!i)return!1;i[c]=e;a.data(b,"selectbox",i)},_openSelectbox:function(b){var c=this._getInst(b);if(c&&!c.isOpen&&!c.isDisabled){var f=a("#sbOptions_"+c.uid),i=parseInt(a(window).height(),10),j=a("#sbHolder_"+c.uid).offset(),k=a(window).scrollTop(),l=f.prev().height(),i=i-(j.top-k)-l/2,j=this._get(c,"onOpen");f.css({top:l+"px",maxHeight:i-l+"px"});"fade"===
c.settings.effect?f.fadeIn(c.settings.speed):f.slideDown(c.settings.speed);a("#sbToggle_"+c.uid).addClass(c.settings.classToggleOpen);this._state[c.uid]=e;c.isOpen=e;j&&j.apply(c.input?c.input[0]:null,[c]);a.data(b,"selectbox",c)}},_closeSelectbox:function(b){var c=this._getInst(b);if(c&&c.isOpen){var e=this._get(c,"onClose");"fade"===c.settings.effect?a("#sbOptions_"+c.uid).fadeOut(c.settings.speed):a("#sbOptions_"+c.uid).slideUp(c.settings.speed);a("#sbToggle_"+c.uid).removeClass(c.settings.classToggleOpen);
this._state[c.uid]=!1;c.isOpen=!1;e&&e.apply(c.input?c.input[0]:null,[c]);a.data(b,"selectbox",c)}},_newInst:function(a){return{id:a[0].id.replace(/([^A-Za-z0-9_-])/g,"\\\\$1"),input:a,uid:Math.floor(99999999*Math.random()),isOpen:!1,isDisabled:!1,settings:{}}},_getInst:function(b){try{return a.data(b,"selectbox")}catch(c){throw"Missing instance data for this selectbox";}},_get:function(a,c){return a.settings[c]!==b?a.settings[c]:this._defaults[c]}});a.fn.selectbox=function(b){var c=Array.prototype.slice.call(arguments,
1);return"string"==typeof b&&"isDisabled"==b||"option"==b&&2==arguments.length&&"string"==typeof arguments[1]?a.selectbox["_"+b+"Selectbox"].apply(a.selectbox,[this[0]].concat(c)):this.each(function(){"string"==typeof b?a.selectbox["_"+b+"Selectbox"].apply(a.selectbox,[this].concat(c)):a.selectbox._attachSelectbox(this,b)})};a.selectbox=new c;a.selectbox.version="0.1.3"})(jQuery);var UTILS=UTILS||{};UTILS.VERSION="0.1";UTILS.AUTHORS="GING";
UTILS.Auth=function(a,b){var c=[];return{initialize:function(a){JSTACK.Keystone.init(a)},authenticate:function(a,d,g,f,i,j){var k=function(){console.log("Authenticated with tentant");i()},l=function(){console.log("Authenticated without tentants. Retrieving tenants...");JSTACK.Keystone.gettenants(function(a){c=a.tenants;m()})},m=function(a){0<c.length?(a=a||c.pop(),console.log("Authenticating for tenant "+JSON.stringify(a.id)),JSTACK.Keystone.authenticate(b,b,JSTACK.Keystone.params.token,a.id,k,n)):
(console.log("Error authenticating"),j("No tenant"))},n=function(){m()},o;g!=b?(o=k,console.log("Authenticating with tenant")):a!=d?(o=l,console.log("Authenticating without tenant")):f!=b&&(o=l,console.log("Authenticating with token"));JSTACK.Keystone.authenticate(a,d,f,g,o,function(){j("Bad credentials")})},getToken:function(){return JSTACK.Keystone.params.token},getName:function(){return JSTACK.Keystone.params.access.user.name},isAuthenticated:function(){return JSTACK.Keystone.params.currentstate==
JSTACK.Keystone.STATES.AUTHENTICATED},getCurrentTenant:function(){return JSTACK.Keystone.params.access.token.tenant},getTenants:function(a){return JSTACK.Keystone.gettenants(function(b){a(b.tenants)})},switchTenant:function(a,c,g){JSTACK.Keystone.authenticate(b,b,JSTACK.Keystone.params.token,a,c,g)},isAdmin:function(){var a=JSTACK.Keystone.params.access.user.roles,b;for(b in a)if("admin"==a[b].name)return!0;return!1}}}(UTILS);
UTILS.Render=function(a,b){return{animateRender:function(a,e,d,g){var f=e(d);$(a).append(f);$(f).hide();$(a).animate({marginLeft:"+1250px",marginRight:"-1250px"},200,function(){$(f).show();$(a).html(f).css("marginLeft","1250px").css("marginRight","-1250px").animate({marginLeft:"-=1250px",marginRight:"+=1250px"},200,function(){g!=b&&g()})});return f}}}(UTILS);
UTILS.i18n=function(a,b){function c(c){var e=$(c),f=e.find("*[data-i18n]");f.each(function(i,j){var j=$(f[i],c),k=a.i18n.get(j.attr("data-i18n"));if(k!=b){var l=j.clone();j.text(k);e.find(l).replaceWith(j)}});return e}function e(a){for(var b=a.split("%"),c=b[0],e=/^([ds])(.*)$/,j=1;j<b.length;j++)if((p=e.exec(b[j]))&&null!=arguments[j])"d"==p[1]?c+=parseInt(arguments[j],10):"s"==p[1]&&(c+=arguments[j]),c+=p[2];return c}return{params:{lang:"en",dict:{}},init:function(){_.extend(_,{itemplate:function(b){var c=
_.template(b);return function(b){b=c(b);return b=a.i18n.translate(b)}}});localStorage.i18nlang==b&&(localStorage.i18nlang="en");UTILS.i18n.setlang(localStorage.i18nlang);console.log("Language: "+localStorage.i18nlang)},setlang:function(c,e){var f="locales/"+c+".json?random="+99999*Math.random();$.ajax({url:f,success:function(i){console.log("loaded: "+f);a.i18n.params.dict=i;localStorage.i18nlang=c;e!=b&&e()},error:function(){console.log("failed loading: "+f);e!=b&&e()},dataType:"json"})},translate:function(a){(new Date).getTime();
a=c(a);(new Date).getTime();return a},get:function(c){var e=a.i18n.params.dict[c];e==b&&(e=c);return e},pluralise:function(b,c,f){b=a.i18n.get(b);1!=f&&(b=a.i18n.get(c));return e(b,f)}}}(UTILS);UTILS.i18n.init();
